### ISSUE TITLE
Smarter truncation scheme

### ISSUE THREAD

**Issue by JohnGiorgi** [JohnGiorgi/t2t#12]
# Overview

[This paper](https://arxiv.org/abs/1905.05583) recently performed a series of empirical experiments on fine-tuning BERT. Among other things, they devised various truncation scheme to handle BERT/ALBERT/RoBERTa's limit of 512 wordpiece tokens.

The best performing scheme involves selecting the first 128 and the last 382 tokens of a document (if the length after wordpiece tokenization exceeds 512). This performs better in text classification tasks. The motivation is that these tokens typically contain the most information within a document.

## TODO

- [ ] Subclass the Seq2Seq dataset reader and add a class attribute that controls the truncation strategy. 
- [ ] Add the above truncation scheme as an option.
- [ ] If it outperforms our current truncation scheme, make it the default.

**Comment by JohnGiorgi** [comment]
I am closing this for now. AllenNLP recently added support for breaking up documents into chunks of 512 tokens and embedding each chunk indepedently. I think I would opt to use that if document length becomes a problem.
